### ISSUE TITLE
mdt-gui failing after installation (debian 7)

### ISSUE THREAD

**Issue by ofgulban** [cbclab/MDT#2]
After following the installation instructions in a python virtual environment:
``` bash
sudo apt install python3 python3-pip python3-pyopencl \
    python3-numpy python3-nibabel python3-pyqt5 \
    python3-matplotlib python3-six python3-yaml \
    python3-argcomplete libpng-dev libfreetype6-dev libxft-dev
sudo pip3 install mdt
```

```mdt-gui``` command returns the following in terminal:

``` bash
Traceback (most recent call last):
  File "/usr/local/bin/mdt-gui", line 7, in <module>
    from mdt.cli_scripts.mdt_gui import GUI
  File "/usr/local/lib/python3.4/dist-packages/mdt/__init__.py", line 16, in <module>
    from mdt.configuration import get_logging_configuration_dict
  File "/usr/local/lib/python3.4/dist-packages/mdt/configuration.py", line 31, in <module>
    from mot.factory import get_optimizer_by_name, get_sampler_by_name
  File "/usr/local/lib/python3.4/dist-packages/mot/factory.py", line 1, in <module>
    from mot.cl_routines.optimizing.grid_search import GridSearch
  File "/usr/local/lib/python3.4/dist-packages/mot/cl_routines/optimizing/grid_search.py", line 5, in <module>
    from ...cl_routines.optimizing.base import AbstractParallelOptimizer, AbstractParallelOptimizerWorker
  File "/usr/local/lib/python3.4/dist-packages/mot/cl_routines/optimizing/base.py", line 4, in <module>
    from mot.cl_routines.mapping.error_measures import ErrorMeasures
  File "/usr/local/lib/python3.4/dist-packages/mot/cl_routines/mapping/error_measures.py", line 2, in <module>
    from ...cl_routines.base import CLRoutine
  File "/usr/local/lib/python3.4/dist-packages/mot/cl_routines/base.py", line 1, in <module>
    from mot import configuration
  File "/usr/local/lib/python3.4/dist-packages/mot/configuration.py", line 32, in <module>
    'cl_environments': CLEnvironmentFactory.smart_device_selection(),
  File "/usr/local/lib/python3.4/dist-packages/mot/cl_environments.py", line 255, in smart_device_selection
    cl_environments = CLEnvironmentFactory.all_devices()
  File "/usr/local/lib/python3.4/dist-packages/mot/cl_environments.py", line 234, in all_devices
    if device_supports_double(device):
  File "/usr/local/lib/python3.4/dist-packages/mot/utils.py", line 45, in device_supports_double
    return cl_device.get_info(cl.device_info.DOUBLE_FP_CONFIG) == 63
pyopencl.LogicError: clGetDeviceInfo failed: invalid value

```

**Comment by robbert-harms** [comment]
Hej Faruk, thanks for reporting it. 

It for some reason failed to detect the device capability. Not an MDT thing perse but more an problem with either the OpenCL driver on your computer or the PyOpenCL package. Nevertheless, I added exception handling to MOT such that it will not fail on this point. 

If you do 'pip uninstall mot' and then 'pip install mot' you can get the latest version of the optimization library containing the update.

Best,

Robbert

**Comment by ofgulban** [comment]
Thanks Robbert,

Actually I was not properly using conda for python3 but fixed it now. After installing again and upgrading MOT the following message shows up with ```MDT``` command:

``` bash
Traceback (most recent call last):
  File "/home/faruk/miniconda3/bin/MDT", line 7, in <module>
    from mdt.cli_scripts.MDT import GUI_Shortcut
  File "/home/faruk/miniconda3/lib/python3.5/site-packages/mdt/__init__.py", line 16, in <module>
    from mdt.configuration import get_logging_configuration_dict
  File "/home/faruk/miniconda3/lib/python3.5/site-packages/mdt/configuration.py", line 31, in <module>
    from mot.factory import get_optimizer_by_name, get_sampler_by_name
  File "/home/faruk/miniconda3/lib/python3.5/site-packages/mot/factory.py", line 1, in <module>
    from mot.cl_routines.optimizing.grid_search import GridSearch
  File "/home/faruk/miniconda3/lib/python3.5/site-packages/mot/cl_routines/optimizing/grid_search.py", line 5, in <module>
    from ...cl_routines.optimizing.base import AbstractParallelOptimizer, AbstractParallelOptimizerWorker
  File "/home/faruk/miniconda3/lib/python3.5/site-packages/mot/cl_routines/optimizing/base.py", line 4, in <module>
    from mot.cl_routines.mapping.error_measures import ErrorMeasures
  File "/home/faruk/miniconda3/lib/python3.5/site-packages/mot/cl_routines/mapping/error_measures.py", line 2, in <module>
    from ...cl_routines.base import CLRoutine
  File "/home/faruk/miniconda3/lib/python3.5/site-packages/mot/cl_routines/base.py", line 1, in <module>
    from mot import configuration
  File "/home/faruk/miniconda3/lib/python3.5/site-packages/mot/configuration.py", line 32, in <module>
    'cl_environments': CLEnvironmentFactory.smart_device_selection(),
  File "/home/faruk/miniconda3/lib/python3.5/site-packages/mot/cl_environments.py", line 255, in smart_device_selection
    cl_environments = CLEnvironmentFactory.all_devices()
  File "/home/faruk/miniconda3/lib/python3.5/site-packages/mot/cl_environments.py", line 223, in all_devices
    platforms = cl.get_platforms()
  File "/home/faruk/miniconda3/lib/python3.5/site-packages/pyopencl/cffi_cl.py", line 670, in get_platforms
    _handle_error(_lib.get_platforms(platforms.ptr, platforms.size))
  File "/home/faruk/miniconda3/lib/python3.5/site-packages/pyopencl/cffi_cl.py", line 632, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clGetPlatformIDs failed: <unknown error -1001>

```

any ideas to solve this issue?

Here is my pip list if you would like to see:
```
appdirs (1.4.1)
argcomplete (1.8.2)
cffi (1.9.1)
conda (4.2.13)
cryptography (1.7.1)
cycler (0.10.0)
decorator (4.0.11)
grako (3.19.1)
h5py (2.6.0)
idna (2.2)
Mako (1.0.4)
MarkupSafe (0.23)
matplotlib (2.0.0)
mdt (0.9.25)
mot (0.2.32)
nibabel (2.1.0)
numpy (1.12.0)
packaging (16.8)
pip (9.0.1)
py (1.4.32)
pyasn1 (0.1.9)
pycosat (0.6.1)
pycparser (2.17)
pycrypto (2.6.1)
pydicom (0.9.9)
pyopencl (2016.2.1)
pyOpenSSL (16.2.0)
pyparsing (2.1.10)
pytest (3.0.6)
python-dateutil (2.6.0)
pytools (2016.2.6)
pytz (2016.10)
PyYAML (3.12)
requests (2.13.0)
ruamel-yaml (-VERSION)
scipy (0.18.1)
setuptools (27.2.0)
six (1.10.0)
tornado (4.4.2)
wheel (0.29.0)

```

**Comment by robbert-harms** [comment]
Hej Faruk,

It looks like an OpenCL issue to me, they can be quite vague. Can you run "clinfo" command for me to check the status of OpenCL on your computer? If not available you can install it with "apt install clinfo". 

If that gives the same sort of error or shows no OpenCL devices then we have found the culprit. 

You are probably using an nvidia card. If so, you could try installing the "nvidia-modprobe" package with apt. Some internet fora suggest that that might solve the issue.

Thanks for your patience and for helping me out,

Best,

Robbert

**Comment by ofgulban** [comment]
Thanks Robbert, 

clinfo returns:
```Segmentation fault```
nvidia-modprobe returns:
```modprobe: FATAL: Module nvidia not found.```

My GPU is Nvidia Quadro K2000.

I am not willing to install nvidia drivers on this computer though due to ongoing analyses, however I will try installing MDT on my laptop (also debian 7) sometime next week and update you.

**Comment by seareel** [comment]
Hi,

I have a similar issue on CentOS 7.2 (see below, using `conda` and `pip` to install the MDT dependencies). This is installed on a machine with an i5 and nvidia k620, although I do not wish to use the OpenCL capability of the nvidia card at the moment.
```
Traceback (most recent call last):
  File "/home/scmcc2/miniconda2/envs/pythonMDT/bin/mdt-gui", line 7, in <module>
    from mdt.cli_scripts.mdt_gui import GUI
  File "/home/scmcc2/miniconda2/envs/pythonMDT/lib/python3.5/site-packages/mdt/__init__.py", line 16, in <module>
    from mdt.configuration import get_logging_configuration_dict
  File "/home/scmcc2/miniconda2/envs/pythonMDT/lib/python3.5/site-packages/mdt/configuration.py", line 31, in <module>
    from mot.factory import get_optimizer_by_name, get_sampler_by_name
  File "/home/scmcc2/miniconda2/envs/pythonMDT/lib/python3.5/site-packages/mot/factory.py", line 1, in <module>
    from mot.cl_routines.optimizing.grid_search import GridSearch
  File "/home/scmcc2/miniconda2/envs/pythonMDT/lib/python3.5/site-packages/mot/cl_routines/optimizing/grid_search.py", line 5, in <module>
    from ...cl_routines.optimizing.base import AbstractParallelOptimizer, AbstractParallelOptimizerWorker
  File "/home/scmcc2/miniconda2/envs/pythonMDT/lib/python3.5/site-packages/mot/cl_routines/optimizing/base.py", line 4, in <module>
    from mot.cl_routines.mapping.error_measures import ErrorMeasures
  File "/home/scmcc2/miniconda2/envs/pythonMDT/lib/python3.5/site-packages/mot/cl_routines/mapping/error_measures.py", line 2, in <module>
    from ...cl_routines.base import CLRoutine
  File "/home/scmcc2/miniconda2/envs/pythonMDT/lib/python3.5/site-packages/mot/cl_routines/base.py", line 1, in <module>
    from mot import configuration
  File "/home/scmcc2/miniconda2/envs/pythonMDT/lib/python3.5/site-packages/mot/configuration.py", line 32, in <module>
    'cl_environments': CLEnvironmentFactory.smart_device_selection(),
  File "/home/scmcc2/miniconda2/envs/pythonMDT/lib/python3.5/site-packages/mot/cl_environments.py", line 255, in smart_device_selection
    cl_environments = CLEnvironmentFactory.all_devices()
  File "/home/scmcc2/miniconda2/envs/pythonMDT/lib/python3.5/site-packages/mot/cl_environments.py", line 223, in all_devices
    platforms = cl.get_platforms()
  File "/home/scmcc2/miniconda2/envs/pythonMDT/lib/python3.5/site-packages/pyopencl/cffi_cl.py", line 670, in get_platforms
    _handle_error(_lib.get_platforms(platforms.ptr, platforms.size))
  File "/home/scmcc2/miniconda2/envs/pythonMDT/lib/python3.5/site-packages/pyopencl/cffi_cl.py", line 632, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clGetPlatformIDs failed: <unknown error -1001>
```

**Comment by robbert-harms** [comment]
Hello Seareel,

Your problem is also related to missing OpenCL drivers for your machine. Without device drivers MDT can not find your devices and hence can do no computations. 

If you are only interested in using your Intel i5 CPU for the computations you could just install the Intel OpenCL drivers for your system: https://software.intel.com/en-us/articles/opencl-drivers#latest_CPU_runtime

Additionally, to test if you have a working OpenCL environment you could install the `clinfo` package ( `yum install clinfo`) and type `clinfo` on the command line to view the devices it found. 

Best,

Robbert

**Comment by seareel** [comment]
Hi Robbert,

thanks a lot for coming back to me and for your suggestion.

I had the OpenCL SDK from intel installed already, I assumed it was containing the driver. I've now installed `clinfo` and the OpenCL driver from the link you provided.

I am quite new to OpenCL's working and I would say it looks like the driver is installed (see below), however I am not sure why `pyopencl` is not seeing that platform.
Short `clinfo --list`
```
Platform #0: NVIDIA CUDA
 `-- Device #0: Quadro K620
Platform #1: Intel(R) OpenCL
 `-- Device #0: Intel(R) Core(TM) i5-4590T CPU @ 2.00GHz
```
Long `clinfo`
```
 Platform Name                                   Intel(R) OpenCL
Number of devices                                 1
  Device Name                                     Intel(R) Core(TM) i5-4590T CPU @ 2.00GHz
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 1.2 (Build 25)
  Driver Version                                  1.2.0.25
  Device OpenCL C Version                         OpenCL C 1.2 
  Device Type                                     CPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               4
  Max clock frequency                             2000MHz
  Device Partition                                (core)
    Max number of sub-devices                     4
    Supported partition types                     by counts, equally, by names (Intel)
  Max work item dimensions                        3
  Max work item sizes                             8192x8192x8192
  Max work group size                             8192
  Preferred work group size multiple              128
  Preferred / native vector sizes                 
    char                                                 1 / 32      
    short                                                1 / 16      
    int                                                  1 / 8       
    long                                                 1 / 4       
    half                                                 0 / 0        (n/a)
    float                                                1 / 8       
    double                                               1 / 4        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    64, Little-Endian
  Global memory size                              8105897984 (7.549GiB)
  Error Correction support                        No
  Max memory allocation                           2026474496 (1.887GiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        262144
  Global Memory cache line                        64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             480
    Max size for 1D images from buffer            126654656 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 480
    Max number of write image args                480
  Local memory type                               Global
  Local memory size                               32768 (32KiB)
  Max constant buffer size                        131072 (128KiB)
  Max number of constant args                     480
  Max size of kernel argument                     3840 (3.75KiB)
  Queue properties                                
    Out-of-order execution                        Yes
    Profiling                                     Yes
    Local thread execution (Intel)                Yes
  Prefer user sync for interop                    No
  Profiling timer resolution                      1ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
    SPIR versions                                 1.2
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Device Extensions                               cl_khr_icd cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_3d_image_writes cl_intel_exec_by_local_thread cl_khr_spir cl_khr_fp64
```

**Comment by seareel** [comment]
Further to the above error, launching Python (3.5.1) and:
```
import pyopencl as cl
platforms = cl.get_platforms()
```
produces:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scmcc2/miniconda2/envs/pythonMDT/lib/python3.5/site-packages/pyopencl/cffi_cl.py", line 670, in get_platforms
    _handle_error(_lib.get_platforms(platforms.ptr, platforms.size))
  File "/home/scmcc2/miniconda2/envs/pythonMDT/lib/python3.5/site-packages/pyopencl/cffi_cl.py", line 632, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clGetPlatformIDs failed: <unknown error -1001>
```
As `clinfo` seems to be seeing the platforms on my machine fine, I guess it could be an issue with PyOpenCL not getting the right info about the driver.

**Comment by seareel** [comment]
Ok, following the previous post, I ran a `strace` on `mdt-gui` and discovered that it was using the `libOpenCL.so.1` from my `conda` environment (installed by PyOpenCL).

After removing the `libOpenCL.so` related files and symlinks in that folder, I created symlinks to the libOpenCL.so installed by the Intel driver recommended by Robbert.

Now `mdt-gui` launches. I haven't tried functionality yet.

I am not sure why the libOpenCL.so provided by PyOpenCL causes that issue. Maybe this applies to the initial post.

Thank you for setting me on a track Robbert !

Cyril

**Comment by robbert-harms** [comment]
Hej Cyril,

Thank you for coming back with your solution. I will add a summary of this conversation to the Install guide and/or FAQ since this is something more people may struggle with. 

I hope MDT now works for you. If not, please let me know and I will try my best to help you out.

Best,

Robbert

**Comment by ofgulban** [comment]
@robbert-harms and @seareel  thanks for the useful discussion and suggestions. I have installed intel opencl drivers however unlike Cyril I am still getting ```segmentation fault``` from ```clinfo```. I believe this is the source of my problems and maybe not related to MDT. I have no idea how to continue from here.

**Comment by robbert-harms** [comment]
Hej Faruk,

There are now newer OpenCL drivers that can use the CPU for the computations, "pocl" it is called. I don't have a Debian machine, but I think it can be installed with: "sudo apt-get install libpocl1-common". You won't be able to run it on your GPU with it, but at least you should be able to use MDT.

Best,

Robbert

**Comment by ofgulban** [comment]
Thanks Robbert,
I will try it once I am back in office, and report what happened.
Faruk

**Comment by ofgulban** [comment]
Sure, I have already updated it. Closing the issue since it is solved now.
